name: 🐛 Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: ['bug, untriaged']
projects: ["opensearch-project/Website Update Project"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened? 
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Details
      description: Add any other context about the problem here.
      value: |
        **Plugins**
        Please list all plugins currently enabled.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.

        **Host/Environment (please complete the following information):**
         - OS: [e.g. iOS]
         - Version [e.g. 22]

        **Additional context**
        Add any other context about the problem here.
    validations:
      required: false