name: 🎉 Become an OpenSearch Solutions Provider
description: Become an OpenSearch Solutions Provider
title: "[SolutionsProvider]  "
labels: ['enhancement, untriaged']
projects: ["opensearch-project/Website Update Project","opensearch-project/Partner Updates and Additions"]

body:
  - type: markdown
    attributes:
      value: "# Become an OpenSearch Solutions Provider! 🎉"
  - type: markdown
    attributes:
      value: |
        Welcome!
        Please take the time to fill out this new Solutions Provider request.
        We will review your submission and get back to you as soon as possible.


  - type: markdown
    attributes:
      value: "## Org information"  
  - type: input
    attributes:
      label: Organization Name
      description: Please let us know the exact business name
      placeholder: Example Inc.
    validations:
      required: true
  - type: input
    attributes:
      label: Main office location
      placeholder: City, Country
    validations:
      required: true   
  - type: dropdown
    attributes:
      label: What regions of the world do you serve?
      description: Select all that apply
      multiple: true
      options:
        - Global
        - Africa
        - Asia Pacific
        - Australia
        - Central America
        - Europe
        - Middle East
        - North America
        - South America
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Business description
      description: A clear and concise description of your business. We will use this to help create your Solutions Provider page.
      placeholder: We are a ...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Business Type
      description: Select all that apply
      multiple: true
      options:
        - Consultancy
        - Independent Software Vendor (ISV)
        - Managed Service Provider (MSP)
        - Platform Integrator
        - Professional Services
        - Support
        - Systems Integrator
        - Training
      default: 0
    validations:
      required: true

  - type: input
    attributes:
      label: URL 
      description: Please provide the URL to your organization's website.
      placeholder: https://www.example.com
    validations:
      required: true

  - type: input
    attributes:
      label: Contact Email
      placeholder: Info@example.com (Where can customers contact you?)
    validations:
      required: true
  - type: input
    attributes:
      label: Contact Phone
      placeholder: (xxx) xxx-xxxx (Where can customers contact you?)
    validations:
      required: false


  - type: markdown
    attributes:
      value: "## What is your product and specialty? "
  - type: markdown
    attributes:
      value: |
        What does your organization specialize in? 
        What products and services do you offer to the OpenSearch community?
  - type: dropdown
    attributes:
      label: Industry Specialization
      description: Select all that apply
      multiple: true
      options:
        - Software and Technology
        - Business Services
        - Consumer Services
        - Education
        - Financial Services
        - Energy and Utilities
        - Government
        - Public Sector
        - Nonprofit
        - Healthcare
        - Media and Entertainment
        - Retail
        - Telecommunications
      default: 0
    validations:
      required: true 
  - type: textarea
    attributes:
      label: Product description
      description: A clear and concise description of your product(s) and/or services offered to the OpenSearch community.
      placeholder: We offer...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OpenSearch Specialty
      description: Select all that apply
      multiple: true
      options:
        - Analytics
        - Logs and Metrics
        - Migration
        - Machine Learning and AI
        - Observability
        - Other
        - Search
        - Security
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Logo and Branding "
  - type: markdown
    attributes:
      value: |
        We use the logo and branding to create your Solutions Provider page and display your organization's information.
        Either provide a URL to your logo or attach your logo to this issue.
  
  - type: input
    attributes:
      label: Logo 
      placeholder: Logo
    validations:
      required: true 
  - type: input
    attributes:
      label: Favicon
      description: Square image - preferably 192x192 pixels
      placeholder: Favicon
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Social Media"
  - type: input
    attributes:
      label: Twitter 
      placeholder: /twitter.com/example
    validations:
      required: false
  - type: input
    attributes:
      label: LinkedIn 
      placeholder: /linkedin.com/example
    validations:
      required: false
  - type: input
    attributes:
      label: Facebook 
      placeholder: /facebook.com/example
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: "## Blog posts and Articles"
  - type: markdown
    attributes:
      value: |
        Add links to you latest three blog posts that are relevant for the OpenSearch Project audience. 
  - type: textarea
    attributes:
      label: Blog posts
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Additional Information "
  - type: markdown
    attributes:
      value: |
        Provide any additional content that you would like to include on your Solutions Provider page.
        You may paste rich text, images, or links to videos.
  - type: textarea
    attributes:
      label: Additional Information
    validations:
      required: false
